### ISSUE TITLE
Action fails to resolve package when installed with `poetry`

### ISSUE THREAD

**Issue by AbstractUmbra** [jakebailey/pyright-action#10]
Sorry for the poorly explained issue.

I'm using your action in a context with `poetry` (using the `snok/install-poetry` action).

It seems that unless I explicitly use `pip install .` to install the deps manually then the action fails to resolve the output.
Here is both my config and an action output from a `pip install .`:
Config: https://github.com/AbstractUmbra/Hondana/blob/7abb4b7f648a4fff4213210e20e0d9767014577c/.github/workflows/coverage_and_lint.yaml#L63-L79
Action: https://github.com/AbstractUmbra/Hondana/actions/runs/4145028232/jobs/7168844087 (Run Pyright step)

Here it is with a poetry installed one:
Config: https://github.com/AbstractUmbra/Hondana/blob/a8653a55a0208a371f9b7248f1bfe8824472066d/.github/workflows/coverage_and_lint.yaml#L57-L71
Action: https://github.com/AbstractUmbra/Hondana/actions/runs/4145136918/jobs/7169102398

I assume this is related to how `pyright` itself resolves the venv path. I asked about this in another [issue](https://github.com/microsoft/pyright/issues/2726) and locally on my server this works fine as you can see here:
```sh
$ poetry install                                   
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: Hondana (3.4.7)

$ poetry run python3 -c "import sys; print(sys.path)"
['', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/home/penumbra/.cache/pypoetry/virtualenvs/hondana-epKOD00U-py3.9/lib/python3.9/site-packages', '/home/penumbra/projects/personal/hondana']

$ poetry run pyright                                 
No configuration file found.
pyproject.toml file found at /home/penumbra/projects/personal/hondana.
Loading pyproject.toml file at /home/penumbra/projects/personal/hondana/pyproject.toml
Assuming Python version 3.9
Assuming Python platform Linux
stubPath /home/penumbra/projects/personal/hondana/typings is not a valid directory.
Searching for source files
Found 68 source files
pyright 1.1.290
0 errors, 0 warnings, 0 informations 
Completed in 5.04sec
```

I'm now wondering if perhaps my config is incorrect or so?

**Comment by AbstractUmbra** [comment]
Upon further investigation it seems that the `sys.path` was not populating with the venv path. I'm unsure if the action here tries to do this when supplied with `venv-path: ` in the config, however I tried manually activating the venv and checking `sys.path` [here](https://github.com/AbstractUmbra/Hondana/actions/runs/4145525936/jobs/7170004063) and it does have the correct venv location but the action still fails to resolve. I believe I'm at a bit of a loss.

**Comment by jakebailey** [comment]
I can tell you that in general, `--venv-path` is not a configuration you want to use unless you're working on Eric's team 😅

`--venv-path` is documented as "Directory that contains virtual environments" (see https://github.com/microsoft/pyright/blob/main/docs/command-line.md) because his team tests multiple versions of python and they store them in one common directory. If you provide venvPath, you also need to need to set in `pyrightconfig.json` a `venv` to specify which subdirectory you need to use.

I suspect what you actually need to do here is to "activate" the envionment just like you would a venv, so that later actions run within that environment. Something like:

```
source $(poetry env info --path)/bin/activate
```

See: https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment

Maybe there's a more canonical way to do poetry activation in GitHub Actions, but this action generally relies on the right Python being in $PATH.

**Comment by jakebailey** [comment]
Note that in your working example above, you are doing `poetry run pyright`, which is running pyright within that envionment. But this action doesn't do that; you have to activate the environment instead.

**Comment by jakebailey** [comment]
Also, if you checkout the README of https://github.com/snok/install-poetry, they are using another method to activate the environment before doing anything, so, I think you probably need to be doing the same.

**Comment by AbstractUmbra** [comment]
In my followup comment I mentioned that I did do this, and checked the path required. I will try more and figure it out, thanks!

**Comment by jakebailey** [comment]
Oh, sorry, I glossed over that! In that case you should just drop the extra venv related flags (they look like they're still set in that example).

**Comment by AbstractUmbra** [comment]
In this run here: https://github.com/AbstractUmbra/Hondana/actions/runs/4146095151/jobs/7171414849
You can see that the venv gets activated and `python3` can find the package and even execute it's `__main__.py` so I'm at even more of a loss.

**Comment by AbstractUmbra** [comment]
To the extent of my knowledge a `poetry install` *does* install it?

```sh
  poetry run pip uninstall hondana -y
WARNING: Skipping hondana as it is not installed.

$ poetry install                     
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: Hondana (3.4.7)

$ pyright --ignoreexternal --lib --verifytypes hondana 
Module name: "hondana"
Package directory: "/home/penumbra/projects/personal/hondana/hondana"
Module directory: "/home/penumbra/projects/personal/hondana/hondana"
Path of py.typed file: "/home/penumbra/projects/personal/hondana/hondana/py.typed"

Public modules: 44
   hondana
   hondana.__main__
   hondana.artist
   hondana.author
   hondana.chapter
   hondana.client
   hondana.collections
   hondana.cover
   hondana.custom_list
   hondana.enums
   hondana.errors
   hondana.forums
   hondana.http
   hondana.legacy
   hondana.manga
   hondana.query
   hondana.relationship
   hondana.report
   hondana.scanlator_group
   hondana.tags
   hondana.types_
   hondana.types_.account
   hondana.types_.artist
   hondana.types_.auth
   hondana.types_.author
   hondana.types_.chapter
   hondana.types_.common
   hondana.types_.cover
   hondana.types_.custom_list
   hondana.types_.errors
   hondana.types_.forums
   hondana.types_.legacy
   hondana.types_.manga
   hondana.types_.relationship
   hondana.types_.report
   hondana.types_.scanlator_group
   hondana.types_.settings
   hondana.types_.statistics
   hondana.types_.tags
   hondana.types_.token
   hondana.types_.upload
   hondana.types_.user
   hondana.user
   hondana.utils

Symbols used in public interface:

Symbols exported by "hondana": 2143
  With known type: 2143
  With ambiguous type: 0
  With unknown type: 0
    (Ignoring unknown types imported from other packages)
  Functions without docstring: 108
  Functions without default param: 11
  Classes without docstring: 29

Other symbols referenced but not exported by "hondana": 72
  With known type: 72
  With ambiguous type: 0
  With unknown type: 0

Type completeness score: 100%

Completed in 2sec

$ pip show hondna                                     
WARNING: Package(s) not found: hondna

$ pip show hondana
Name: hondana
Version: 3.4.7
Summary: An asynchronous wrapper around the MangaDex v5 API
Home-page: https://github.com/AbstractUmbra/hondana
Author: Alex Nørgaard
Author-email: Umbra@AbstractUmbra.dev
License: MIT
Location: /home/penumbra/.cache/pypoetry/virtualenvs/hondana-epKOD00U-py3.9/lib/python3.9/site-packages
Requires: aiohttp, typing-extensions
Required-by: 
```

**Comment by jakebailey** [comment]
Hm, I'll have to try this locally.

Just to fully confirm, are you intentionally passsing `--verifytypes`, or are you just aiming to typeheck your project? You really only want to pass the flag when you want to check type completeness. I can't recall whether or not it'll also check other things.

**Comment by AbstractUmbra** [comment]
I'm intentionally trying to call that, yes. Sorry for the confusion, I was a bit confused by this whole thing myself!

**Comment by jakebailey** [comment]
Oh, this I'm pretty sure this is just failing because the workflow activates the environment in one step, but then tries to use it in the next. Environment variables don't make it outside of a step unless you explicitly tell GitHub Actions to do so.

If you tack `echo PATH=$PATH >> $GITHUB_ENV` onto the end of your activation step, it should work.

**Comment by AbstractUmbra** [comment]
Hmm no dice it seems?
https://github.com/AbstractUmbra/Hondana/actions/runs/4146326340/jobs/7171835589

**Comment by jakebailey** [comment]
Also just some notes on the workflow (now that I'm actually back at my machine to read it, sorry 😅)

- You don't have to set `no-comments`; if `--verifytypes` is passed, the action disables any of the "smart" stuff and just runs pyright as though it were a regular CLI run.
- Generally, you don't want to pass `--lib` when doing verifytypes; your types can potentially depend on another's and so you're enabling some extra inference that users may not actually have. (They probably will, if they're using pylance, but not so much elsewhere).
- I should probably add `ignoreexternal` to the list of options; not sure why I am missing that one.

**Comment by jakebailey** [comment]
Bleh, still failed. Really confusing.

**Comment by AbstractUmbra** [comment]
I'll sort those out just now then, thank you!

Yeah it sure is

**Comment by jakebailey** [comment]
The only think I can think is that this has to do with the way that the workflow is getting poetry and caching packages; if I expand out the info at the top of the pyright step, the info there is the only thing that differs from my local testing.

Can you try the more simplified way to get poetry and cached dependences from here? https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

So something like:

```yml
steps:
- uses: actions/checkout@v3
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v4
  with:
    python-version: "${{ matrix.python-version }}"
    cache: 'poetry'
- run: poetry install
- run: |
    source $(poetry env info --path)/bin/activate
    echo PATH=$PATH >> $GITHUB_ENV
- uses: jakebailey/pyright-action@v1
  ...

**Comment by AbstractUmbra** [comment]
Even with basically just the above the basic action with no `--verifytypes` fails, it seems to fail resolving the venv again?
https://github.com/AbstractUmbra/Hondana/actions/runs/4148240881/jobs/7176028170

With `--verifytypes`:
https://github.com/AbstractUmbra/Hondana/actions/runs/4148252197/jobs/7176053293

Also a side note, the config I use for the `--verifytypes` runner seems to always enable json output. Is this intended?

**Comment by jakebailey** [comment]
Really confusing. I'll have to see, but I won't be at my PC for a while.

Regarding JSON, uh, hm. Can you drop back to v1.4.2 and see if I accidentally broke it in v1.5.0?

**Comment by AbstractUmbra** [comment]
1.4.2 is the same coincidentally!

**Comment by jakebailey** [comment]
Okay good, if I accidentally broke it in that last version I wouldn't be able to fix it for a bit. Phew.

I'll try and look into the rest of this but I'm on a plane right now 😅

**Comment by AbstractUmbra** [comment]
Oh, no rush! Have a safe flight!

**Comment by jakebailey** [comment]
I totally forgot about this; are you still having trouble or did this manage to go away?

**Comment by AbstractUmbra** [comment]
Still an issue sadly!
Here's the latest run: 
<https://github.com/AbstractUmbra/Hondana/actions/runs/4337957513/jobs/7574313843>

**Comment by jakebailey** [comment]
I got it to work on my fork: https://github.com/jakebailey/Hondana/actions/runs/4338086216/jobs/7574524776

I think this just comes down to ensuring poetry is fetched in the right way + added to PATH (GITHUB_ENV apparently does not work).

I need to fix the JSON problem which is related to the way I'm mishandling `--verifytypes`, but after I release again it should all work.

**Comment by jakebailey** [comment]
Success! https://github.com/jakebailey/Hondana/actions/runs/4338182182/jobs/7574692258

**Comment by jakebailey** [comment]
FYI here's the workflow: https://github.com/jakebailey/Hondana/actions/runs/4338086216/workflow

I would recommend trimming your poetry setup to something like this:

```yml
      - uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      
      - run: poetry install
      
      - run: |
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - run: python -c 'import sys, json; json.dump(sys.path, sys.stdout, indent=4)'
      
      - uses: jakebailey/pyright-action@v1
        with:
          verify-types: "hondana"
          ignore-external: true
```

**Comment by nikebless** [comment]
Just wanted to thank you @jakebailey for this!

**Comment by jakebailey** [comment]
I've gone and stuck an example of this into the README so I don't have to point people here.
