### ISSUE TITLE
Can't get annotations to run on repo code

### ISSUE THREAD

**Issue by AbstractUmbra** [jakebailey/pyright-action#100]
Hey!

Firstly I want to add that I think this is a me issue and not a *you* issue, haha.

I cannot get the action to annotate my codebase/PRs/commits, as it is designed to do and I'm struggling to figure out why.

The repo I'll use is [this one](https://github.com/AbstractUmbra/Mipha). The job for running this action is [here](https://github.com/AbstractUmbra/Mipha/blob/a651aa094b8d818cffb506320ce230032ff59ea1/.github/workflows/coverage_and_lint.yaml#L69-L73). If you check the history of that file you can see I edited it a few times as a test.

Any help would be appreciated but I understand if it's out of scope for this issue tracker!

**Comment by jakebailey** [comment]
Reading a log like https://github.com/AbstractUmbra/Mipha/actions/runs/8326990796/job/22783729972, I don't see any reason why they wouldn't show up... In the below, the colored lines are the annotations:

![image](https://github.com/jakebailey/pyright-action/assets/5341706/0f6b3420-a5ae-4cb8-9121-c3b34e47d1a9)

So, I'm inclined to believe that this is a GitHub issue, or maybe some sort of repo configuration problem? Not really aware of how that's possible, though.

**Comment by AbstractUmbra** [comment]
Yeah I seen those and figured this would then annotate the code within the UI browser or maybe even in the actioned commit (as I've seen in other repos using this action).

Very unusual, thanks for taking a look at least, it's much appreciated!
