### ISSUE TITLE
Failures in GitHub on pyright `1.1.373` but no Pylance failures on the same pyright version

### ISSUE THREAD

**Issue by tylerlaprade** [jakebailey/pyright-action#137]
### GitHub Action
![image](https://github.com/user-attachments/assets/27da0bab-3e3c-4821-8afd-c6e240daaac9)

#### Version number
<img width="562" alt="image" src="https://github.com/user-attachments/assets/c0ebe3ad-dda3-4851-8077-8e8ae5d599a7">
#### No errors
<img width="548" alt="image" src="https://github.com/user-attachments/assets/019dcdc6-279e-4a83-985d-074b1c25cf61">

### Latest release
https://github.com/microsoft/pylance-release/blob/main/releases/latest-release.json

**Comment by jakebailey** [comment]
If you run `pyright` on your codebase straight from npm via like `npx pyright@1.1.373`, do the erros also appear? This action is just shorthand for pulling it and running it, so I doubt this is the action's doing (rather, maybe a missed fix between pylance/pyright).

**Comment by tylerlaprade** [comment]
Oh yeah, good call. I see the errors in the CLI as well, so I guess the problem is on Pyright's side.
<img width="445" alt="image" src="https://github.com/user-attachments/assets/d0ff9e17-02ab-4b50-a203-decbefe99f90">

**Comment by jakebailey** [comment]
Yeah, you'd have to report this to Pylance, as it's possible they're missing this change.
