### ISSUE TITLE
Module resolution change

### ISSUE THREAD

**Issue by camflan** [jakebailey/pyright-action#2]
Looks like `1.1.168` broke our CI pipelines. The errors indicate that pyright isn't able to resolve some of our stubs/typings. Unfortunately, I don't see anything obvious in the last couple commits :/

Pinning the action to `1.1.167` restores proper functionality.
Python 3.9.6

**Comment by jakebailey** [comment]
Please open an issue on the pyright repo; this action is a thin wrapper that only runs pyright.

There were some changes recently to visibility rules, but I'm not sure that's what you are experiencing.
