### ISSUE TITLE
Question: what's the recommended way to get stubs installed?

### ISSUE THREAD

**Issue by ikamensh** [jakebailey/pyright-action#3]
Hi, thanks for this GH action!

I'm trying to use it with a venv so that the library stubs are available, but I still get this error:
`error: Import "numpy" could not be resolved (reportMissingImports)`
https://github.com/openai/gym/runs/4526885810

Any hint on what I'm doing wrong? Since pyright doesn't complain about venv, I assume I have passed the path correctly.

**Comment by ikamensh** [comment]
The reason was not using `venv` setting, only `venvPath`.

**Comment by jakebailey** [comment]
I'd actually recommend activating the environment instead and letting pyright figure it out via PATH; IIRC the intent of `venvPath` and `venv` is more intended for teams with common interpreter layouts (which is how Eric's team had it set up when he wrote the tool).

**Comment by benglewis** [comment]
@jakebailey I'm also a little confused about this. Do I need to actually copy the stubs into my codebase?

**Comment by jakebailey** [comment]
This action just runs pyright; where to put stubs is a question for them.

I would think not. You should get stubs either bundled with pyright, or get them from PyPI
