### ISSUE TITLE
Support --verifytypes

### ISSUE THREAD

**Issue by AbstractUmbra** [jakebailey/pyright-action#4]
Hello!

I'm not even sure where to begin with this bug report.

I believe I have either misunderstood how to set up this action, or it will not catch obvious errors.

I noticed it during [this run](https://github.com/AbstractUmbra/Hondana/runs/5523276909?check_suite_focus=true), where the `Type Coverage` step passed successfully, however there were numerous type errors relating to return type were completely missed.
My action specification at the time looked [like this](https://github.com/AbstractUmbra/Hondana/blob/f8cf30d523e9b9264e818bad467515297c718c8a/.github/workflows/coverage_and_lint.yaml#L25-L28), which should have inherited from the `pyproject.toml` file outlined [here](https://github.com/AbstractUmbra/Hondana/blob/f8cf30d523e9b9264e818bad467515297c718c8a/pyproject.toml).

I have managed to manually install node, and run pyright manually in an action to verify that it will actually return these results, this can be viewed [here](https://github.com/AbstractUmbra/Hondana/runs/5523448716?check_suite_focus=true) in the "Run Pyright" step.

Could you please let me know if this is an issue with the action, or me? I very much like and appreciate the features you offer.

**Comment by jakebailey** [comment]
This pyright action doesn't support the `--verifytypes` flag, which you seem to be using in your second manual run.

**Comment by AbstractUmbra** [comment]
Oh that would definitely do it, thanks for letting me know. In that case, would a feature request for this be feasible?

**Comment by jakebailey** [comment]
It's definitely on my mental list. The question I was debating was what the pass-fail condition would be.

**Comment by AbstractUmbra** [comment]
In my uneducated opinion, I suppose any `error` type would be a fail, but `warning` and `info` would pass?

**Comment by jakebailey** [comment]
In the type verifier mode, I don't think either are actually emitted.

The mode is also intended to be run on the installed version of a library (not locally on a repo), so I'm also questioning how that might work in CI either.

**Comment by AbstractUmbra** [comment]
Oh I also forgot about that, currently I run an install step prior to this, which obviously isn't ideal.

**Comment by jakebailey** [comment]
I've added rudimentary support for `--verifytypes` in v1.0.5. There's no special GitHub integration, and a score under 100% will fail the build (e.g. matching the exit code of pyright).
