### ISSUE TITLE
Fails for Pyright version `1.1.330.post0`

### ISSUE THREAD

**Issue by superlopuh** [jakebailey/pyright-action#51]
The latest version of Pyright seems not to parse

**Comment by superlopuh** [comment]
Just had a quick look at the source code, it seems that there's a [line where the version is parsed by SemVer](https://github.com/jakebailey/pyright-action/blob/34c9e23b7e64dae051936c6c2acfbd9d3f334337/src/helpers.ts#L69C34-L69C34), and it might not support the syntax, maybe that should be in some try/catch block.

**Comment by jakebailey** [comment]
This is not a version listed on npm: https://www.npmjs.com/package/pyright?activeTab=versions

Where are you seeing this version?

**Comment by jakebailey** [comment]
It seems like you're trying to parse the version of the PyPI package (https://pypi.org/project/pyright/#history); this is a third party package unsupported by those who work on `pyright` and its versions are not valid for use in this action.
