### ISSUE TITLE
The newest pyright version is 1.1.331 but action prints 1.1.332

### ISSUE THREAD

**Issue by Kamilcuk** [jakebailey/pyright-action#53]
The newest version on pypi https://pypi.org/project/pyright/ is 1.1.331:

**Comment by Kamilcuk** [comment]
Looks like it was just deployed upstream, please ignore, sorry

**Comment by jakebailey** [comment]
FWIW the PyPI package is not maintained by the pyright maintainers or myself. The canonical place to find pyright is on npm.
