### ISSUE TITLE
`Unexpected end of JSON input` error when using action vs locally

### ISSUE THREAD

**Issue by cbrxyz** [jakebailey/pyright-action#7]
Hola! Thanks for helping to make such a great tool that makes type checking our team's Python much easier! 😄

I've been trying to implement `pyright` into a GitHub Actions pipeline recently, and I've kept running into this error. Pyright should be pretty up to date, and what's weird is that if I run it locally (with the same flags, including the version/platform/JSON flags), it works fine. A nice big blob of JSON is output.

I wonder if it's just too much JSON for one part of the program to handle? Running the same command locally produces ~17000 lines of JSON output.

Here's the output of our GitHub Actions step, if that helps:
<details>
<summary>GitHub Actions output</summary>

```
pyright 1.1.260, node v16.13.0, pyright-action 1.3.0
/actions-runner/externals/node16/bin/node /opt/hostedtoolcache/pyright/1.1.260/x64/package/index.js --outputjson --pythonplatform Linux --pythonversion 3.8 NaviGator/gnc/navigator_controller/nodes/gps_to_baselink_odom.py NaviGator/gnc/navigator_controller/nodes/mrac_controller.py ...other python files...

Loading configuration file at /tmp/runners/diamond/work/mil/mil/pyrightconfig.json

stubPath /tmp/runners/diamond/work/mil/mil/typings is not a valid directory.

Searching for source files

Found 443 source files

**Error: Unexpected end of JSON input**
```
</details>

Here's our `pyrightconfig.json` file, too, if that helps in debugging:
<details>
<summary>pyrightconfig.json</summary>

```json
{
    "exclude": [
        "deprecated",
        "docs",
        "NaviGator/simulation/VRX",
        "NaviGator/perception/darknet_ros"
    ],
    "reportMissingTypeStubs": false,
    "pythonVersion": "3.8",
    "pythonPlatform": "Linux"
}

```
</details>

Thank you for your time. Have a good weekend!

**Comment by jakebailey** [comment]
I highly suspect this is a buffering problem with the child process; node's stdio support is really fickle and when I made this action, I had to make a bunch of changes to pyright in order to ensure that it didn't exit before it had a change to write all of its output.

I haven't seen any changes to pyright's CLI output code, so I'm going to guess that this is now a buffering problem on the action's side because it reads the output over stdin. (If it comes to it, I could probably modify pyright to write data via IPC or something; that would probably be a good change no matter what.)

On your local copy, can you pipe the JSON output to a file and then tell me its size in bytes?

**Comment by cbrxyz** [comment]
Sure, looks to be about 700KB.
```bash
$ pyright NaviGator/gnc/navigator_controller/nodes/gps_to_baselink_odom.py ... --outputjson --pythonplatform=Linux --pythonversion=3.8 > test.json
$ wc -c test.json
727669 
```

**Comment by jakebailey** [comment]
Hm, that doesn't seem all that large, really.

Is this repo available for me to test with, by chance?

**Comment by cbrxyz** [comment]
Thanks for looking into this. You should be able to clone our repo (https://github.com/uf-mil/mil) - it's a bit of a monorepo, so it's not super tiny, unfortunately.

We've recently started migrating our Python 2 code to Python 3 on the `noetic-migration` branch, so you'll just need to check out that branch after cloning. The work done on the GitHub Actions pipeline has been on `noetic-ci-improvements`, which branched off of `noetic-migration` a few days ago.

That should be enough to at least run `pyright`!

**Comment by jakebailey** [comment]
I was able to copy the command run from your CI task and run it locally; the size of the output for the most recent run is actually ~1.4MB. The default buffer size Node uses for child processes is 1MB, so it's probable that this is part of the problem (the output is so huge). I can try and bump this number up higher and see if that helps, but it's definitely the case that your project is so huge that things are really hitting the limit (especially given pyright uses `JSON.stringify` to produce its output, which is not streaming).

**Comment by jakebailey** [comment]
Can you try out v1.4.0, which I've just released?

**Comment by cbrxyz** [comment]
Works like a charm; thank you Jake! Sorry about reporting the incorrect size of the errors earlier.
