### ISSUE TITLE
How to set venv?

### ISSUE THREAD

**Issue by flying-sheep** [jakebailey/pyright-action#8]
For some reason, PyRight makes one specify `venvPath` together with `venv`.

How to specify a venv with this action? `extra-args: '--venv=...'` doesn’t seem to work (“unexpected option `--venv`”)

**Comment by jakebailey** [comment]
I don't recommend using venv/venvPath in pyright at all; the option is pretty specific to Eric's team's monorepo. For normal use, you should be getting the right venv onto PATH, or the right interpreter selected in your editor in the Python extension.

If you have a venv in CI, you will have much better success activating it in a previous step, but largely, it doesn't seem all that common to actually use a venv in CI.

**Comment by jakebailey** [comment]
I'm pretty sure the error is because those options can only be set in a config file, not via a flag. Which, again, is the byproduct of how this option works in pyright.

**Comment by jakebailey** [comment]
I've stuck some usage examples in the README to make this clearer.
